monorepo_root = true

[monorepo]
config_roots = [".", "cli", "typescript", "python"]

[tools]
# keep this version inline with the version declared in .github/workflows/typescript
bun = "1.3.14"
# keep this version inline with rust stable
rust = "1.96.0"
# keep this version inline with the version declared in .github/workflows/python
uv = "0.11.21"
