# This config file sets up PubMedQA to use the Gemini API, and sets up the SimpleQA-verified
# benchmark to use the internal demo model.
#
# The PubMedQA benchmark reads the Gemini API key from the `GEMINI_API_KEY` environment
# variable. Learn more about the Gemini API in Google's Gemini AI Studio:
#
# https://aistudio.google.com/prompts/new_chat


[benchmarks.pubmedqa]
# The full expert-labeled PubMedQA benchmark has 1000 samples. Since Google charges for
# usage, we are limiting the number of samples to 50 in this demo, to keep costs lower.
samples = 50

# The below model is good for demonstrating PubMedQA benchmarks without very high costs,
# since it's relatively cheap and fast. Details on the model can be found at:
#
# https://ai.google.dev/gemini-api/docs/models/gemini#gemini-3.1-flash-lite
#
# That page also lists other Google models you can use.
model = "gemini:gemini-3.1-flash-lite"

# If you run this or other benchmarks with more samples, you may also need to increase this
# `max_workers` parameter to improve throughput. If you do so, however, you will likely
# run into rate limits, because Google's default rate limits are relatively strict.
#
# See the following rate limit and quota page for more information:
#
# https://aistudio.google.com/rate-limit
max_workers = 10

# If you don't want to use a hosted/paid model, you can omit model configuration and
# use the built-in demo model. Note, however, that this built-in model emits random text, and
# should only be used for testing purposes.
[benchmarks.simpleqa-verified]
samples = 100
