[benchmarks.nocode_custom]
type = "custom_nocode"
style = { type = "exact_match", golden_column = "answer" }
dataset = { name = "quantiles/simpleqa-verified" }
model = "random"
prompt_template_file = "prompts/qa.txt"
limit = 10

[benchmarks.medqa]
type = "custom_nocode"
dataset = { name = "quantiles/MedQA-USMLE-4-options", config_name = "default", split = "test" }
model = "random"
prompt_template_file = "prompts/medqa.txt"
limit = 10

[benchmarks.medqa.style]
type = "multiple_choice"
choices = { column = "options" }
choice_labels = ["A", "B", "C", "D"]
answer = { label_column = "answer_idx" }

[benchmarks.medmcqa]
type = "custom_nocode"
dataset = { name = "quantiles/medmcqa", config_name = "default", split = "validation" }
model = "random"
prompt_template_file = "prompts/medmcqa.txt"
limit = 100

[benchmarks.medmcqa.style]
type = "multiple_choice"
choices = { columns = ["opa", "opb", "opc", "opd"] }
choice_labels = ["A", "B", "C", "D"]
answer = { index_column = "cop", index_base = 0 }

[benchmarks.mmlu-pro]
type = "custom_nocode"
dataset = { name = "quantiles/MMLU-Pro", config_name = "default", split = "test" }
model = "random"
prompt_template_file = "prompts/mmlu-pro.txt"
limit = 1000

[benchmarks.mmlu-pro.style]
type = "multiple_choice"
choices = { column = "options" }
choice_labels = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
answer = { label_column = "answer" }

# The MMLU-pro benchmark configured to use OpenAI's gpt-5.6-luna model.
#
# You can customize any custom_nocode eval to use one of a variety of LLM providers.
# See the following documentation for details:
#
# https://quantiles.io/documentation/configuration#customizing-the-model
#
# Read more about the gpt-5.6-luna model here:
#
# https://developers.openai.com/api/docs/models/gpt-5.6-luna
#
# And read more about the MMLU-pro benchmark here:
#
# https://arxiv.org/abs/2406.01574
[benchmarks.mmlu-pro-gpt-5-6]
type = "custom_nocode"
dataset = { name = "quantiles/MMLU-Pro", config_name = "default", split = "test" }
model = "openai:gpt-5.6-luna"
prompt_template_file = "prompts/mmlu-pro.txt"
limit = 100

[benchmarks.mmlu-pro-gpt-5-6.style]
type = "multiple_choice"
choices = { column = "options" }
choice_labels = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
answer = { label_column = "answer" }

# The GPQA benchmark configured to use the random model
#
# Read more about GPQA here:
#
# https://arxiv.org/abs/2311.12022
[benchmarks.gpqa]
type = "custom_nocode"
model = "random"
prompt_template_file = "prompts/gpqa.txt"
dataset = { name = "quantiles/gpqa", config_name = "gpqa_diamond", split = "train" }

[benchmarks.gpqa.style]
type = "multiple_choice"
choices = { columns = ["Correct Answer", "Incorrect Answer 1", "Incorrect Answer 2", "Incorrect Answer 3"] }
choice_labels = ["A", "B", "C", "D"]
answer = { correct_choice_column = "Correct Answer" }
shuffle = { seed_column = "Record ID" }
