[benchmarks.pubmedqa]
dataset = "hf://quantiles/PubMedQA"
samples = 10

[benchmarks.simpleqa-verified]
dataset = "hf://quantiles/simpleqa-verified"
samples = 100

[benchmarks.financebench]
dataset = "hf://quantiles/financebench"
samples = 50
