# This config file sets up PubMedQA to use the Cloudflare AI gateway, and sets up the SimpleQA-verified
# benchmark to use the internal demo model.
#
# The PubMedQA benchmark reads the Cloudflare account ID, gateway ID, and API key
# from the following environment variables:
#
# - CLOUDFLARE_ACCOUNT_ID
# - CLOUDFLARE_GATEWAY_ID
# - CLOUDFLARE_API_KEY
#
# To get your account ID, gateway ID and API key, go to your Cloudflare AI gateway dashboard at:
#
# https://dash.cloudflare.com/<account_id>/ai/ai-gateway

[benchmarks.pubmedqa]
# The full expert-labeled PubMedQA benchmark has 1000 samples. Since Cloudflare charges for
# usage, we are limiting the number of samples to 50 in this demo, to keep costs lower.
samples = 50

# The following model is good for demonstrating PubMedQA benchmarks without very high costs,
# since it's relatively cheap, fast, and not a reasoning model. Its details can be found at:
#
# https://developers.cloudflare.com/workers-ai/models/llama-3.3-70b-instruct-fp8-fast/
#
# And a list of all models can be found at:
#
# https://developers.cloudflare.com/workers-ai/models/
model = "cloudflare_ai_gateway:@cf/meta/llama-3.3-70b-instruct-fp8-fast"

# If you don't want to specify your account ID and gateway ID in environment variables
# (CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_GATEWAY_ID, respectively), you can provide them
# alongside the model in a dictionary as below:
#
# model = {
#   type = "cloudflare_ai_gateway:@cf/meta/llama-3.3-70b-instruct-fp8-fast",
#   account_id = "...",
#   gateway_id = "..."
# }
#
# Note that if you do this, you will still need to provide the API key in the
# CLOUDFLARE_API_KEY environment variable.
