# This config file sets up PubMedQA to use the OpenAI API, and sets up the SimpleQA-verified
# benchmark to use the internal demo model.
#
# The PubMedQA benchmark reads the OpenAI API key from the `OPENAI_API_KEY` environment variable.
#
# Learn more about the OpenAI API at:
#
# https://platform.openai.com/home

[benchmarks.pubmedqa]
# The full expert-labeled PubMedQA benchmark has 1000 samples. Since OpenAI charges for
# usage, we are limiting the number of samples to 50 in this demo, to keep costs lower.
samples = 50

# The following model is good for demonstrating PubMedQA benchmarks without very high costs,
# since it's relatively cheap and fast. You may need to ensure the project associated with
# your API key has permissions to use this model. Do so by going to the follwing page, and
# enabling the model:
#
# https://platform.openai.com/settings/$PROJECT_ID/limits
#
# Details on this specific model can be found at:
#
# https://developers.openai.com/api/docs/models/gpt-5.5-nano
#
# And a list of all models can be found at:
#
# https://developers.openai.com/api/docs/models/all
model = "openai:gpt-5.6"

# If you run this or other benchmarks with more samples, you may also need to increase this
# `max_workers` parameter to improve throughput. This might cause you to run into rate
# limits, because the defaults are relatively low. To increase them, scroll down
# on the same https://platform.openai.com/settings/$PROJECT_ID/limits page and adjust limits
# for the model you're using.
max_workers = 100
