[tasks.test]
run = "uv run python -m pytest"

[tasks.lint]
run = "uv run ruff check ."

[tasks.fmt-check]
run = "uv run ruff format . --check"

[tasks.fmt]
run = [
    "uv run ruff format .",
    "uv run ruff check . --fix"
]

[tasks.typecheck]
run = "uv run ty check"


[tasks.all]
depends = ["fmt", "lint", "typecheck", "test"]

[tasks.ci]
run = [
    "uv sync",
    "mise run ci-checks",
]

[tasks.ci-checks]
depends = [
    "fmt-check",
    "lint",
    "typecheck",
    "test",
]

[tasks.wheel-build]
run = "uv build"

[tasks.wheel-publish]
run = "uv publish --token $PYPI_TOKEN"
