name: cli

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: check
    runs-on: ubuntu-24.04
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_WEBDAV_ENDPOINT: https://cache.depot.dev
      SCCACHE_WEBDAV_TOKEN: ${{ secrets.SCCACHE_WEBDAV_TOKEN }}
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: .
      - uses: jdx/mise-action@v2
        with:
          version: 2026.6.11
          # TODO: consider cache: true
          # https://github.com/marketplace/actions/mise-action#example-workflow
      - name: Ensure rustfmt and clippy are installed for pinned Rust version
        run: mise x -- rustup component add rustfmt clippy --toolchain 1.96.0
      - name: Run CLI checks
        run: mise //cli:ci
